apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: es
  name: es
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: es
    spec:
      containers:
      - env:
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.3
        livenessProbe:
          exec:
            command:
            - curl --silent --fail localhost:9200/_cluster/health || exit 1
        name: es
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: es-claim0
      restartPolicy: Always
      volumes:
      - name: es-claim0
        persistentVolumeClaim:
          claimName: es-claim0
status: {}
