apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: privoxy
  name: privoxy
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: privoxy
    spec:
      containers:
      - image: sirboops/privoxy
        name: privoxy
        resources: {}
        volumeMounts:
        - mountPath: /opt/config
          name: privoxy-claim0
      restartPolicy: Always
      volumes:
      - name: privoxy-claim0
        persistentVolumeClaim:
          claimName: privoxy-claim0
status: {}
