apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - args:
        - bash
        - -c
        - rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000 -b '0.0.0.0'
        env:
        - name: ALLOW_ACCESS_TO_HIDDEN_SERVICE
          valueFrom:
            configMapKeyRef:
              key: ALLOW_ACCESS_TO_HIDDEN_SERVICE
              name: web-env-production
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              key: DATABASE_URL
              name: web-env-production
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              key: DB_HOST
              name: web-env-production
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              key: DB_NAME
              name: web-env-production
        - name: DB_PASS
          valueFrom:
            configMapKeyRef:
              key: DB_PASS
              name: web-env-production
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              key: DB_PORT
              name: web-env-production
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              key: DB_USER
              name: web-env-production
        - name: ES_ENABLED
          valueFrom:
            configMapKeyRef:
              key: ES_ENABLED
              name: web-env-production
        - name: ES_HOST
          valueFrom:
            configMapKeyRef:
              key: ES_HOST
              name: web-env-production
        - name: ES_PORT
          valueFrom:
            configMapKeyRef:
              key: ES_PORT
              name: web-env-production
        - name: GID
          valueFrom:
            configMapKeyRef:
              key: GID
              name: web-env-production
        - name: LOCAL_DOMAIN
          valueFrom:
            configMapKeyRef:
              key: LOCAL_DOMAIN
              name: web-env-production
        - name: OAUTH_REDIRECT_AT_SIGN_IN
          valueFrom:
            configMapKeyRef:
              key: OAUTH_REDIRECT_AT_SIGN_IN
              name: web-env-production
        - name: OTP_SECRET
          valueFrom:
            configMapKeyRef:
              key: OTP_SECRET
              name: web-env-production
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              key: REDIS_HOST
              name: web-env-production
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              key: REDIS_PORT
              name: web-env-production
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              key: REDIS_URL
              name: web-env-production
        - name: SECRET_KEY_BASE
          valueFrom:
            configMapKeyRef:
              key: SECRET_KEY_BASE
              name: web-env-production
        - name: STREAMING_CLUSTER_NUM
          valueFrom:
            configMapKeyRef:
              key: STREAMING_CLUSTER_NUM
              name: web-env-production
        - name: UID
          valueFrom:
            configMapKeyRef:
              key: UID
              name: web-env-production
        - name: VAPID_PRIVATE_KEY
          valueFrom:
            configMapKeyRef:
              key: VAPID_PRIVATE_KEY
              name: web-env-production
        - name: VAPID_PUBLIC_KEY
          valueFrom:
            configMapKeyRef:
              key: VAPID_PUBLIC_KEY
              name: web-env-production
        - name: http_proxy
          valueFrom:
            configMapKeyRef:
              key: http_proxy
              name: web-env-production
        image: tootsuite/mastodon
        livenessProbe:
          exec:
            command:
            - 'wget -q --spider --header ''x-forwarded-proto: https'' --proxy=off
              localhost:3000/api/v1/instance || exit 1'
        name: web
        ports:
        - containerPort: 3000
        resources: {}
        volumeMounts:
        - mountPath: /mastodon/public/system
          name: web-claim0
      restartPolicy: Always
      volumes:
      - name: web-claim0
        persistentVolumeClaim:
          claimName: web-claim0
status: {}
